config/routes.rb
Subasta::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  resources :users do
    resources :auctions
    resources :investments
    resources :wallets
    resources :choices
  end

  resources :auctions do
    resources :bids
  end

  resources :bids do
    resources :investments
  end
  
  resources :wallets do
    resources :investments
  end
  
  resources :choices
  resources :investments

  
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

end

app/models/bid.rb
class Bid < ActiveRecord::Base
	belongs_to :auction
	belongs_to :user
	has_many :investments, dependent: :destroy


	default_scope -> { order('created_at DESC') }
	scope :by_team, where(category: 'team')
	#scope :by_player, where(category: 'player', auction_id: auction.id)
	scope :by_pg, where(subcategory: 'pg')
	scope :by_sg, where(subcategory: 'sg')
	scope :by_sf, where(subcategory: 'sf')
	scope :by_pf, where(subcategory: 'pf')
	scope :by_ce, where(subcategory: 'ce')



	validates :user_id, presence: true
	validates :auction_id, presence: true
	validates :name, presence: true
	validates :category, presence: true
	#validates :actual_amount_id, allow_nil: true
	#validates :subcategory, presence: true
	validates_numericality_of :price, :only_integer => true, presence: true
	validates_numericality_of :max_amount, :only_integer => true, presence: true
	validates_numericality_of :actual_amount, :only_integer => true, presence: true
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
   	before_action :signed_in_user, only: [:create, :destroy,:edit, :update]
	#before_action :correct_user, only: [:destroy,:edit, :update]
	#before_action :auth_requirements_one, only: [:create,:destroy,:edit, :update]
	before_action :admin_user, only: [:create,:destroy,:edit, :update]
	
	def create
		@bid= Bid.create(bid_params)
		@bid.actual_amount=@bid.price
		@bid.max_amount=@bid.price
		@bid.user_id = current_user.id
		if @bid.save
			flash[:success] = "Bid created!"
			redirect_to auctions_url
		else
			@auctions = Auction.paginate(page: params[:page])
			#@investment = current_user.investments.build
			render 'auctions/index'
		end
	end

	def destroy
		Bid.find(params[:id]).destroy
		redirect_to auctions_url
	end

	def index
	end

	def edit
		@bid = Bid.find(params[:id])
	end

	def update
		@bid = Bid.find(params[:id])
		if @bid.update(bid_params)
			flash[:success] = "Bid updated"
			redirect_to auctions_url
		else
			render 'edit'
		end
	end

	private

		def bid_params
			params.require(:bid).permit(:name,:category,:subcategory,:price,:auction_id)
		end

		def correct_user
			@bid = current_user.bids.find_by(id: params[:id])
			redirect_to root_url if @bid.nil?
		end

		def admin?(user)
		    if not user.nil?
		      return user.admin
		    end
		    return false
	  	end

#		def auth_requirements_one
#			@biduser = current_user.bids.find_by(id: params[:id])
#			if admin?(current_user) || current_user?(@biduser)
#				return true
#			else
#				redirect_to root_url
#			end
#		end
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/views/bids/_bid.html.erb
<small>
	<span class="content">Auction id: <%= bid.auction_id %></span>
	<span class="content">Bid name: <%= bid.name %></span>
	<span class="content">Bid category: <%= bid.category %></span>
	<span class="content">Bid subcategory: <%= bid.subcategory %></span>
	<span class="content">Bid price: <%= bid.price %></span>
	<span class="content">Bid actual amount: <%= bid.actual_amount %></span>
	<span class="content">Bid max amount: <%= bid.max_amount %></span>
	<span class="content">Bid id: <%= bid.id %></span>
	<span class="timestamp">
		Created <%= time_ago_in_words(bid.created_at) %> ago by <%= bid.user.name %>
	</span>
	<% if  admin?(current_user) %>
		<%= link_to "edit", edit_bid_path(bid), data: { confirm: "You sure?" },title: bid.name %>
		<%= link_to "delete", bid, method: :delete, data: { confirm: "You sure?" },title: bid.name %>
	<% end %>
	<div class="span4">
			<ol class="userbids">
				<%= render bid.investments %>
			</ol>
		</div>
		<%if signed_in?%>
		<div class="row">
			<div class="span8">
					<%= render partial: "investments/form", locals: {bid: bid} %>
			</div>
		</div>
		<% end %>
</small>

app/views/bids/_form.html.erb
<%= form_for(@bid) do |f| %>
	<%= f.hidden_field :auction_id, :value => auction.id %>
	<%= render 'shared/error_messages', object: f.object %>
	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name, placeholder: "Name of object..." %>
		<%= f.label :category %>
		<%= f.text_field :category, placeholder: "Category of object..." %>
		<%= f.label :subcategory %>
		<%= f.text_field :subcategory, placeholder: "Subcategory of object..." %>
		<%= f.label :price %>
		<%= f.text_field :price, placeholder: "Price of object..." %>
	</div>
	<%= f.submit "Bid", class: "btn btn-large btn-primary" %>
<% end %>

app/views/bids/edit.html.erb
<% provide(:title, "Edit Bid") %>
	<h1>Update Bid</h1>
	<div class="row">
		<div class="span6 offset3">
			<%= form_for(@bid) do |f| %>
				<%= render 'shared/error_messages', object: f.object %>
				<div class="field">
					<%= f.label :name %>
					<%= f.text_field :name %>
					<%= f.label :category %>
					<%= f.text_field :category %>
					<%= f.label :subcategory %>
					<%= f.text_field :subcategory %>
					<%= f.label :price %>
					<%= f.text_field :price %>
				</div>
					<%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
			<% end %>
		</div>
	</div>