config/routes.rb
Subasta::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  resources :users do
    resources :auctions
    resources :investments
    resources :wallets
    resources :choices
  end

  resources :auctions do
    resources :bids
  end

  resources :bids do
    resources :investments
  end
  
  resources :wallets do
    resources :investments
  end
  
  resources :choices
  resources :investments

  
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :auctions , dependent: :destroy
	has_many :bids, dependent: :destroy
	has_many :investments, dependent: :destroy
	has_one  :wallet, dependent: :destroy
	has_one  :choice, dependent: :destroy

	#before_save { self.email = email.downcase }
	before_save { email.downcase! }
	before_create :create_remember_token

	validates :name, presence: true, length: { maximum: 50 }
	#VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, 
		uniqueness: { case_sensitive: false }
	validates :password, length: { minimum: 6 }
	validates_numericality_of :initial_cash, :only_integer => true, presence: true
	validates_numericality_of :actual_cash, :only_integer => true, presence: true
	has_secure_password

	def User.new_remember_token
	    SecureRandom.urlsafe_base64
	end

	def User.digest(token)
	    Digest::SHA1.hexdigest(token.to_s)
	end

	def feed
		Auction.where("user_id = ?", id)
	end

	 private

	   def create_remember_token
	     self.remember_token = User.digest(User.new_remember_token)
	   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :signed_in_user, only: [:index, :edit, :update, :destroy]
    before_action :correct_user,   only: [:edit, :update]
    before_action :admin_user,     only: :destroy

  	def index
      @users = User.paginate(page: params[:page])
    end

  
    def show
    	@user = User.find(params[:id])
      @wallet = Wallet.find_by(user_id: @user.id)
      @choice = Choice.find_by(user_id: @user.id)
  	end

  	def new
  		@user = User.new
  	end

    def create
      @user = User.new(user_params)
      if @user.save 
        sign_in @user
        @wallet = Wallet.new
        @wallet.user_id = current_user.id
        @wallet.initial_cash=1000
        @wallet.actual_cash=1000
        @wallet.save
        @choice=Choice.new
        @choice.user_id = current_user.id
        @choice.save
        flash[:success] = "Welcome to the Sample App!"
        redirect_to @user
      else
        render 'new'
      end
    end

    def edit
      @user = User.find(params[:id])
    end

    def update
      @user = User.find(params[:id])
      if @user.update_attributes(user_params)
        flash[:success] = "Profile updated"
        redirect_to @user
      else
        render 'edit'
      end
    end

    def destroy
      User.find(params[:id]).destroy
      flash[:success] = "User deleted."
      redirect_to users_url
    end

  	private

    	def user_params
      		params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    	end

      # Before filters

      def correct_user
        @user = User.find(params[:id])
        redirect_to(root_url) unless current_user?(@user)
      end

      def auth_requirements_one
        @actualuser = User.find(params[:id])
        if admin?(current_user) || current_user?(@actualuser)
          return true
        else
          redirect_to root_url
        end
      end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
  	| <%= link_to "edit", edit_user_path(user),
                                  data: { confirm: "You sure?" } %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
       <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, "Wallet and Choice of #{@user.name}") %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= @user.name %>
        <% if  current_user.admin? && wallet_created?(@user) %>
          | <%= link_to "wallet", user_wallet_path(@user,@wallet) %>		      
          | <%= link_to "edit_wallet", edit_user_wallet_path(@user,@wallet)%>
          | <%= link_to "delete", user_wallet_path(@user,@wallet), method: :delete, data: { confirm: "You sure?" },title: @user.name %>
        <% elsif  current_user?(@user) && wallet_created?(@user) %>
          | <%= link_to "wallet", user_wallet_path(@user,@wallet) %>
        <% elsif current_user.admin? %>
          | <%= link_to "new_wallet", new_user_wallet_path(@user) %>
    	  <% end %>
      </h1>
      <h1>
        <% if  current_user.admin? && choice_created?(@user) %>
          | <%= link_to "choice", user_choice_path(@user,@choice) %>          
          | <%= link_to "edit_choice", edit_user_choice_path(@user,@choice)%>
          | <%= link_to "delete", user_choice_path(@user,@choice), method: :delete, data: { confirm: "You sure?" },title: @user.name %>
        <% elsif  current_user?(@user) && choice_created?(@user) %>
          | <%= link_to "choice", user_choice_path(@user,@choice) %>
        <% elsif current_user.admin? %>
          | <%= link_to "new_choice", new_user_choice_path(@user) %>
        <% end %>
      </h1>
    </section>
  </aside>
</div>