config/routes.rb
Subasta::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  resources :users do
    resources :auctions
    resources :investments
    resources :wallets
    resources :choices
  end

  resources :auctions do
    resources :bids
  end

  resources :bids do
    resources :investments
  end
  
  resources :wallets do
    resources :investments
  end
  
  resources :choices
  resources :investments

  
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

end

app/views/shared/_auction_form.html.erb
<%= form_for(@auction) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<div class="field">
		<%= f.label :title %>
		<%= f.text_field :title, placeholder: "Title for new auction..." %>
		<%= f.label :content %>
		<%= f.text_area :content, placeholder: "Describe new auction..." %>
	</div>
	<%= f.submit "Auction", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
	<ol class="userauctionss">
		<%= render partial: 'shared/feed_item', collection: @feed_items %>
	</ol>
	<%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li>
	<span class="auctiontitle"><%= feed_item.title %></span>
	<span class="content"><%= simple_format feed_item.content %></span>
	<span class="timestamp">
		Created <%= time_ago_in_words(feed_item.created_at) %> ago by <%= feed_item.user.name %>.
	</span>
	<% if admin?(current_user) %>
		<%= link_to "edit", edit_auction_path(feed_item), data: { confirm: "You sure?" }, title: feed_item.content %>
		<%= link_to "delete", auction_path(feed_item), method: :delete, data: { confirm: "You sure?" }, title: feed_item.content %>
	<% end %>
</li>

app/views/shared/_user_info.html.erb
<h1>
	<%= current_user.name %>
</h1>
<span>
	<%= pluralize(current_user.auctions.count, "auction") %>
</span>